version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
    ports:
      - 5433:5432
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/dashi
    ports:
      - 3000:3000