# Generated by Django 4.0.2 on 2022-03-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('web', models.CharField(blank=True, max_length=40, verbose_name='Ссылка на сайт')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=40, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
            ],
        ),
    ]
