# Generated by Django 4.0.2 on 2022-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('special', models.CharField(max_length=80, verbose_name='Заголовок - выделение')),
                ('titleIcon', models.ImageField(upload_to='images', verbose_name='Картинка для заголовка')),
                ('newsLink', models.CharField(max_length=200, verbose_name='Ссылка на новость')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('subtitleIcon', models.ImageField(upload_to='images', verbose_name='Картинка для подзаголовка')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='background',
            field=models.ImageField(upload_to='images', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
