# Generated by Django 4.0.2 on 2022-03-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_bigbanner_alter_news_background_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigbanner',
            name='subtitleIcon',
            field=models.FileField(upload_to='images', verbose_name='Картинка для подзаголовка'),
        ),
        migrations.AlterField(
            model_name='bigbanner',
            name='titleIcon',
            field=models.FileField(upload_to='images', verbose_name='Картинка для заголовка'),
        ),
    ]
